#端口
server:
  port: 9001

#mybatis
mybatis:
  type-aliases-package: com.example.buyer.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl:org.apache.ibatis.logging.stdout.StdOutImpl

#DataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Car?serverTimezone=UTC&useSSL=false
    username: root
    password: root
