server:
  port: 9999

spring:
  application:
    name: seller
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    encoding: UTF-8
  mvc:
    static-path-pattern=/static/**:
  datasource:
    url: jdbc:mysql://localhost:3306/Car
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tMvWz46FmvU6jgQwEvS
    accessKeySecret: iv0FTtK6X4NZaxhesWNDfao9Nlulbh
    bucketName: example-warning
    fileHost: com/picture
