server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Car?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: lxjroot
    driver-class-name: com.mysql.cj.jdbc.Driver
